### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by SimonZimmer** [y-brehm/waveAlign#2]
We need to add unit testing to the entire codebase

**Comment by maosi100** [comment]
With the latest commits we now have unit tests for most functions. The only one'smissing are [align_waveform_to_target](https://github.com/y-brehm/waveAlign/blob/main/src/wavealign/loudness_processing/align_waveform_to_target.py) and the [main function](https://github.com/y-brehm/waveAlign/blob/main/src/wavealign/batch_process_files.py). The latter is basically just the argparser.

What's your opinion on testing the remaining functions: required to have full coverage or not required due to limited complexity?

**Comment by maosi100** [comment]
issue can be closed after 5d9079c6139b6b96de70ffee862546a73262881f
